Attribute VB_Name = "MGP_Dim"
Public MGP_IN_Name_¹_Dog
Public MGP_IN_Name_DATE
Public MGP_IN_Name_Customer
Public MGP_IN_Name_Product
Public MGP_IN_Name_Company
Public MGP_IN_Name_adress
Public MGP_IN_Name_Dog
Public MGP_IN_Date
